### ISSUE TITLE
Installation fails with python 3.4

### ISSUE THREAD

**Issue by dmitry-saritasa** [elbuo8/sendgrid-django#13]
Hi Guys,

``` python
(python3)[root@backend app]# pip install sendgrid-django==1.3.0
Collecting sendgrid-django==1.3.0
  Downloading sendgrid-django-1.3.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-cldgmrut/sendgrid-django/setup.py", line 16, in <module>
        long_description=open('./README.rst').read(),
      File "/home/www/.virtual/python3/lib/python3.4/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 83: ordinal not in range(128)

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-cldgmrut/sendgrid-django
(python3)[root@backend app]# pip install sendgrid-django       
Collecting sendgrid-django
  Using cached sendgrid-django-1.3.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-9u9wc2e6/sendgrid-django/setup.py", line 16, in <module>
        long_description=open('./README.rst').read(),
      File "/home/www/.virtual/python3/lib/python3.4/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 83: ordinal not in range(128)

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-9u9wc2e6/sendgrid-django
```

**Comment by andriisoldatenko** [comment]
@dmitry-saritasa 
```
(py3.4.5) vagrant@vagrant-ubuntu-trusty-64:~$ pip install sendgrid-django
Collecting sendgrid-django
  Downloading sendgrid-django-3.0.0.tar.gz
Collecting sendgrid<4,>=3 (from sendgrid-django)
  Using cached sendgrid-3.6.0-py2.py3-none-any.whl
Collecting python-http-client>=2.1.1 (from sendgrid<4,>=3->sendgrid-django)
  Using cached python_http_client-2.2.1-py2.py3-none-any.whl
Installing collected packages: python-http-client, sendgrid, sendgrid-django
  Running setup.py install for sendgrid-django ... done
Successfully installed python-http-client-2.2.1 sendgrid-3.6.0 sendgrid-django-3.0.0
You are using pip version 8.1.1, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(py3.4.5) vagrant@vagrant-ubuntu-trusty-64:~$ python -V
Python 3.4.5
```

**Comment by elbuo8** [comment]
@dmitry-saritasa still observing this?

**Comment by kavdev** [comment]
@andriisoldatenko, @elbuo8: Looks like his console only supported ascii (it failed on ``long_description=open('./README.rst').read()``). There were non-ascii apostrophes in your readme file before the @dmitry-saritasa merged in his fixes.

You can close this issue.
